name: demo_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  faker: ^2.1.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  bcrypt: 1.1.3
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  mailer: ^6.1.0
  email_otp: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mongo_dart: ^0.10.0
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/Studio-Project-nobg.png
    - assets/images/2x2_YNSON.png
    - assets/images/bmp.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/bmp.png"
  min_sdk_android: 21
  remove_alpha_ios: true
